#!/bin/sh

#
# Gradle start up script for POSIX generated by Gradle.
#

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME"
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1 ; then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH."
    fi
fi

# Setup the Gradle environment
APP_HOME=$( cd "${APP_HOME:-./}" > /dev/null && pwd -P ) || exit

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the JVM's architecture
JVM_ARCH=$(java -version 2>&1 | head -1 | cut -d' ' -f3 | sed 's/"//g')

# Determine the platform
case "$(uname)" in
  Darwin) platform=darwin ;;
  Linux)  platform=linux ;;
  MINGW*|MSYS*|CYGWIN*) platform=windows ;;
  *) die "Unsupported platform: $(uname)" ;;
esac

GRADLE_OPTS="${GRADLE_OPTS} -Dorg.gradle.appname=nanogram-pc"
GRADLE_USER_HOME="${GRADLE_USER_HOME:-$HOME/.gradle}"

exec "$JAVACMD" \
  $GRADLE_OPTS \
  -classpath "$CLASSPATH" \
  org.gradle.wrapper.GradleWrapperMain \
  "$@"
